package org.packman.server.logic

object DifferentMapPlayer {
    // @TODO (Adel Grishin) create maps
    private val playerMaps = listOf(
        PlayerMap(
            map = listOf(
                intArrayOf(WALL, WALL, WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL),
                intArrayOf(WALL, EMPT, WALL,EMPT,EMPT,EMPT,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,EMPT,WALL,EMPT,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,EMPT,WALL,EMPT,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,EMPT,WALL,WALL,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,WALL,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, WALL, WALL,WALL,WALL,WALL,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, EMPT,EMPT,WALL,EMPT,EMPT,WALL,EMPT,EMPT,PLAY,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,EMPT,WALL,EMPT,WALL,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, WALL,WALL,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, WALL, WALL,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, EMPT, EMPT,EMPT,WALL,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
                intArrayOf(WALL, WALL, WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL),
            ),
            coordinatePlayer = Coordinate(i = 7, j = 10),
            lifeCoins = mutableListOf(),
        )
    )

    fun generateMap() = playerMaps.shuffled().first()

    val emptyMap = listOf(
        intArrayOf(WALL, WALL, WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL),
        intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
        intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
        intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
        intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
        intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
        intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
        intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
        intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
        intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
        intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
        intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
        intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
        intArrayOf(WALL, EMPT, EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,EMPT,WALL),
        intArrayOf(WALL, WALL, WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL),
    )
}

private val EMPT = MapLogic.Companion.ParseMap.EMPTY.value
private val WALL = MapLogic.Companion.ParseMap.WALL.value
private val PLAY = MapLogic.Companion.ParseMap.PLAYER.value